style = "default"
format_docstrings = false
margin = 120
whitespace_ops_in_indices = true
whitespace_typedefs = false
whitespace_in_kwargs = true
short_to_long_function_def = false
remove_extra_newlines = true
import_to_using = false
always_use_return = true
annotate_untyped_fields_with_any = true